### PR TITLE
convert to .NET Framework4.6

### PR DESCRIPTION
**Pull request by tsubakimoto**
Hi.
I converted all projects to `.NET Framework 4.6.1` .
Unit test is all clear.

_120416_032301_pm

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @tsubakimoto,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/csharp-http-client/blob/master/CONTRIBUTING.md#cla">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

**Comment by thinkingserious** [comment]
Hi @tsubakimoto,

This looks good to me, I'll just need the [signed CLA](https://github.com/sendgrid/csharp-http-client/blob/master/CONTRIBUTING.md#cla) to formally review and merge. Thanks

**Comment by thinkingserious** [comment]
Hello @tsubakimoto,

Just checking in. Do you still want this one to be merged? Thanks!

**Comment by tsubakimoto** [comment]
Hello @thinkingserious . Thanks checking.
I want to merge this PR. But, because I am not good at English, the understanding of CLA takes time.
Can I have time to me a little more?

**Comment by thinkingserious** [comment]
Sure @tsubakimoto,

Please let me know if there is anything I can do to help.

**Pull request closed without merging**
