### PR TITLE
Fixed broken feature request link

### PR DESCRIPTION
**Pull request by sanjaysingh**
Fixed broken feature request link

# Fixes # 
Fixes broken feature request link

### Checklist
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
-  Fixes broken feature request link on the readme page
- 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/csharp-http-client?pullRequest=83) <br/>All committers have signed the CLA.

**Comment by sanjaysingh** [comment]
CI build is failing with following error

System.IO.FileNotFoundException : Could not find file "/home/travis/build/sendgrid/csharp-http-client/LICENSE.txt"

It seems unrelated to my changes and i am not sure what to do.

**Comment by sanjaysingh** [comment]
I noticed that license file link was broken as well so updated that. If we can somehow kick the build again it should work.

**Comment by sanjaysingh** [comment]
Still failed. I think license file needs to be renamed to License.txt from License.md. If that is the case i would raise another clean Pull request with the file renamed as well as link to 'feature request' link.

**Comment by crweiner** [comment]
@sanjaysingh There are currently two PRs to fix the Travis errors. The first is in #77, so hopefully it will be merged soon and you don't have to worry about the Travis flag. :+1:

**Comment by thinkingserious** [comment]
Hello @sanjaysingh,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
