### PR TITLE
Added support for .Net Core. Fixes #1

### PR DESCRIPTION
**Pull request by PaitoAnderson**
Notes:
- Converted the project to use the project.json / .xproj format.
- Added support for ASP.Net Core. Fixes #1.
- NUnit tests do still work (See screenshot below)
- I was unable to actually test the example without a sendgrid key.
- I didn't see #2 until after I had this ready, this is pretty similar.
  unittest

### CODE REVIEW

**Comment by thinkingserious** [comment]
This is awesome @PaitoAnderson!

For us to merge your pull request, we will need a signed CLA: https://github.com/sendgrid/csharp-http-client/blob/master/CONTRIBUTING.md#cla

Once you have done that, we'll review for a merge.

With Best Regards,

Elmer

**Comment by PaitoAnderson** [comment]
@thinkingserious Thanks, Signed Contributor Agreement has been emailed.

**Comment by thinkingserious** [comment]
Hello @PaitoAnderson,

Your signed CLA is received and this pull request is now queued for review. Thanks!

With Best Regards,

Elmer

**Comment by cleftheris** [comment]
What is the status on this one. It seems that it has been stalled.

**Comment by thinkingserious** [comment]
@cleftheris please see my response here: https://github.com/sendgrid/sendgrid-csharp/issues/221#issuecomment-226211061

**Comment by thinkingserious** [comment]
Hello @PaitoAnderson,

This has finally bubbled to the top of my queue. Do you mind fixing the conflicts so I can test and merge?

Thanks!

**Comment by colltoaction** [comment]
Would be great to have .NET Core support, LGTM :)

**Comment by thinkingserious** [comment]
@PaitoAnderson @tinchou,

Any thoughts on this comment: https://github.com/sendgrid/sendgrid-csharp/issues/221#issuecomment-249885547?

**Comment by colltoaction** [comment]
Thanks, I didn't realize there were two projects for .NET!

**Pull request closed without merging**
