### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vyaspranjal33**
fixed LICENSE file extension in Link

# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [ ] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- 
- 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/csharp-http-client?pullRequest=84) <br/>All committers have signed the CLA.

**Comment by aroach** [comment]
@vyaspranjal33 Can you take a look at why the build is failing?

**Comment by vyaspranjal33** [comment]
@aroach build fails because of "mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe UnitTest/bin/Release/UnitTest.dll -domain:None" 

please fix it

**Comment by aroach** [comment]
It looks like it's failing when testing for LICENSE.txt: https://travis-ci.org/sendgrid/csharp-http-client/builds/447152699#L1724

**Comment by vyaspranjal33** [comment]
@aroach  i fixed 404 error by changing License file link in badge ,i think it can be merged

**Comment by aroach** [comment]
@vyaspranjal33 yes, i see that.  I didn't notice that the build had been failing on that LICENSE.txt check for a while now.  You're good then!  Thanks for the PR!

**Comment by vyaspranjal33** [comment]
@aroach please merge PRs , today is last day of Hacktoberfest :sweat_smile:

**Comment by thinkingserious** [comment]
Hello @vyaspranjal33,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
