### PR TITLE
Cache default httpclient

### PR DESCRIPTION
**Pull request by nillis**

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @nillis,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/csharp-http-client/blob/master/CONTRIBUTING.md#cla">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

**Comment by nillis** [comment]
#17

**Comment by thinkingserious** [comment]
Hi @nillis,

I believe the test is failing because `private static HttpClient _httpClient = new HttpClient();` should be in the `Client` class rather than the `Response` class.

**Comment by nillis** [comment]
Idd, my bad. New build is running :)

**Comment by thinkingserious** [comment]
Perfect, thanks for the quick fix!

Now, we just need a [signed CLA from you](https://github.com/sendgrid/csharp-http-client/blob/master/CONTRIBUTING.md#cla) in order to review and merge. Thanks again!

**Comment by pkarlapu** [comment]
Hey..Now that this is merged to master, I am wondering when would a new version of NuGet be released.

**Comment by thinkingserious** [comment]
Hi @karlapudipradeep,

You should be able to access this version here: https://www.nuget.org/packages/SendGrid.CSharp.HTTP.Client/3.1.0

With Best Regards,

Elmer

**Comment by pkarlapu** [comment]
@thinkingserious  Cool..Thanks! I mistook this commit as a commit to https://github.com/sendgrid/sendgrid-csharp repo and was excited for a little bit. It seems like there is an issue opened for the other repo at https://github.com/sendgrid/sendgrid-csharp/issues/405. I will try sending a pull request for it when I get a chance.

**Comment by thinkingserious** [comment]
@pkarlapu,

I'm actually reviewing that PR right now: https://github.com/sendgrid/sendgrid-csharp/pull/417 :)

Your feedback would be greatly appreciated. Thanks!

**Pull request merged**
