### PR TITLE
Fix location of LICENSE.md file in Repo

### PR DESCRIPTION
**Pull request by crweiner**
Just as in the other PR's below, this PR fixes links to your `README.md` file so the link is correct to your MIT License. :+1: 

Similar to: 
- https://github.com/sendgrid/sendgrid-java/pull/513
- https://github.com/sendgrid/java-http-client/pull/109

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
Fixes link in `README.md` to the license file, which is proparly located at `LICENSE.md` not `LICENSE.txt`

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/csharp-http-client?pullRequest=82) <br/>All committers have signed the CLA.

**Comment by crweiner** [comment]
I have also just pushed commits to update the location of the `LICENSE.md` file in the following locations:
https://github.com/sendgrid/csharp-http-client/blob/3164990c3f404944a5f21a41ac0ddccef08f0825/nuspec/SendGrid.CSharp.HTTP.Client.3.3.0.nuspec#L8
https://github.com/sendgrid/csharp-http-client/blob/3164990c3f404944a5f21a41ac0ddccef08f0825/UnitTest/UnitTest.cs#L107
https://github.com/sendgrid/csharp-http-client/blob/67a056900efe6f16e032a661842c7de5de675181/README.md#L5

This will hopefully fix one of the Travis errors: https://travis-ci.org/sendgrid/csharp-http-client/builds/446382440#L1724

**Comment by crweiner** [comment]
Good news, this change does now seem to get the Travis build to pass! :smile: :+1: 

https://travis-ci.org/sendgrid/csharp-http-client/builds/446750111

The last successful Travis build of `master` was about a year ago [here](https://travis-ci.org/sendgrid/csharp-http-client/builds). 

That's a +1 for having simple changes solve big problems. :sweat_smile:

**Comment by crweiner** [comment]
I just saw that @AnnaDodson also has a fix for `UnitTest.cs` in PR #77 and Issue #76. :+1: Yay for synergy! :smile: 

Once her PR gets merged to fix Travis, then the location of the `LICENSE.md` file will still need to be changed in the `README.md` and `SendGrid.CSharp.HTTP.Client.3.3.0.nuspec` which should be taken care of by this PR.
https://github.com/sendgrid/csharp-http-client/blob/3164990c3f404944a5f21a41ac0ddccef08f0825/nuspec/SendGrid.CSharp.HTTP.Client.3.3.0.nuspec#L8

**Comment by thinkingserious** [comment]
Hello @crweiner,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
