### PR TITLE
Timeout Parameter

### PR DESCRIPTION
**Pull request by PandaBoy00**

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @PandaBoy00,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/csharp-http-client/blob/master/CONTRIBUTING.md#cla">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

**Comment by thinkingserious** [comment]
Thanks @PandaBoy00!

Could you please resolve the remaining conflict? 

With Best Regards,

Elmer

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/csharp-http-client?pullRequest=23) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/csharp-http-client?pullRequest=23) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/csharp-http-client?pullRequest=23) it.</sub>

**Comment by thinkingserious** [comment]
Thanks for the update @PandaBoy00,

Looks like there is an error:

```
Test Error : UnitTest.TestClient.TestMethodCall Microsoft.CSharp.RuntimeBinder.RuntimeBinderException : `SendGrid.CSharp.HTTP.Client.Response' does not contain a definition for `GetAwaiter'
```

Could you please take a look?

Thanks!

**Comment by PandaBoy00** [comment]
@thinkingserious I have complete the merge and I think I have already signed the CLA.  So all should be good now.

**Comment by thinkingserious** [comment]
Hello @PandaBoy00,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
